policy:
  - section:
      - id: ['report-type']
        block-list: ['None', 'Other']
        label:
          - name: 'report: inventory'
            keys: ['Inventory']
          - name: 'report: quality'
            keys: ['Data quality']
          - name: 'report: product'
            keys: ['Product']
