policy:
  - section:
      - id: ['report-type']
        block-list: ['None', 'Other']
        label:
          - name: 'report: inventory'
            keys: ['Inventory']
          - name: 'report: quality'
            keys: ['Data quality']
          - name: 'report: product'
            keys: ['Product']
        - id: ['submission-type']
          block-list: ['None', 'Other']
          label:
            - name: 'type: new submission'
              keys: ['New Submission']
            - name: 'type: resubmission'
              keys: ['Resubmission']
