name: "Report review request"
description: "Reqest a report review"
title: "[REVIEW]: "
labels: ["review"]
body:
- type: "markdown"
  attributes:
    value: "## Review request"
- type: "markdown"
  attributes:
    value: |
      Thank you for submitting a review request. Please complete the following details. 
- type: "input"
  attributes:
    label: "Report title"
    placeholder: "Report title, as it appears on the submitted report"
  validations:
    required: true
- type: "dropdown"
  id: report-type
  attributes:
    label: "Type of report"
    description: "Select one"
    options:
      - "Report"
      - "Other"
  validations:
    required: true
- type: "dropdown"
  id: submission-type
  attributes:
    label: "Submission type"
    description: "Select one..."
    options:
      - "New submission"
      - "Resubmission"
      - "Major revision"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Message to editors"
    placeholder: "Please confirm the type of report you are submitting, along with a short 1-2 line description. Include anything that the editors should be aware of when reviewing your submission, such as any conflicts of interest. If your submission is a resubmission or a major revision, please also outline the changes from the previous submission."
  validations:
    required: true
- type: "input"
  attributes:
    label: "Git repository of the source file"
    description: "The github link where the .qmd source file is stored."
    placeholder: "For example, https://github.com/username/repository"
  validations:
    required: true
- type: "input"
  attributes:
    label: "Author's Github username"
    description: "Your Github user handle."
    placeholder: "For example, @username"
  validations:
    required: true
- type: "input"
  attributes:
    label: "Link to current compiled .pdf version"
    description: "A publicly-accessible link to the compiled .pdf version of the report."
  validations:
    required: true
- type: "checkboxes"
  attributes:
    label: "Declaration"
    options:
    - label: "I certify that I have the authority to submit this report on behalf of its authors"
      required: true
    - label: "I certify that I have read and understood the review code of conduct"
      required: true
    - label: "I certify that I have read and understood the description of the review process"
      required: true
  validations:
    required: false
